Repository weniv/weniv_world, pull requests merged in 2023-09, with the labels that each got.

#39 📝 PR: 초기화시 캐릭터 정보 노출 오류 수정
  index.html
Labels: bug-fix

#40 📝 PR: 위니브월드 pick 메서드 오류 수정
  assets/py/character.py
Labels: bug-fix

#41 📝 PR: 위니브월드 set_item 메서드 오류 수정
  assets/py/built_in_functions.py
Labels: bug-fix

#45 📝 PR: 위니브월드 함수 자동완성 기능 Disabled
  assets/pyscript/pyscript_latest.js
Labels: feat

#50 📝 PR: 캐릭터 속도 조절 적용 코드 수정
  assets/py/character.py
  index.html
Labels: bug-fix

#54 📝 PR: output 코드 다운로드, 초기화 버튼 위치 수정 #51
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  index.html
Labels: feat

#59 📝 PR: 코드 추가 기능 구현 및 코드 ipynb 파일 추출 기능 구현
  assets/img/icon/icon-file-export.svg
  assets/img/icon/icon-file-import.svg
  assets/js/editor.js
  assets/pyscript/pyscript_latest.js
  index.html
Labels: feat

#60 Feat/editor thema
  assets/css/_notebook.scss
  assets/css/style.css
  assets/css/style.css.map
  index.html
Labels: feat

#65 📝 PR: 벽 아이콘, 색상 수정 #61
  assets/css/_main.scss
  assets/css/_variables.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/img/icon/icon-blocked.svg
  assets/img/icon/icon-door.svg
  assets/img/icon/icon-fence.svg
  assets/js/event.js
  index.html
Labels: feat

#68 📝 PR: output header 추가(#67), 코드 결과 출력 스크롤 하단으로 이동되도록 수정(#35)
  assets/css/_main.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/img/icon/icon-code-download.svg
  assets/img/icon/icon-code-upload.svg
  assets/js/editor.js
  index.html
Labels: feat

#70 Feat/toolbar UI
  assets/css/_main.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/img/icon/icon-polygon.svg
  assets/js/event.js
  index.html
Labels: feat

#72 📝 PR: 아이템 추가 UI 수정 #66
  assets/css/_main.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/img/icon/icon-polygon-dark.svg
  index.html
Labels: feat

#73 📝 PR: 코드 에디터 하단에 코드 추가 버튼 나타나도록 기능 추가 #71
  assets/css/_notebook.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/js/editor.js
Labels: feat

#77 Feat/UI feedback
  assets/css/_main.scss
  assets/css/_notebook.scss
  assets/css/_story.scss
  assets/css/_variables.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/js/setStory.js
Labels: feat

#79 📝 PR: 코드에디터 내 기능 구현
  assets/js/editor.js
  assets/js/event.js
  assets/js/utils.js
  index.html
Labels: feat, bug-fix

#83 📝 PR: Webpack 적용 및 CI/CD 테스트
  assets/py/built_in_functions.py
  assets/py/character.py
  assets/py/coordinate.py
  assets/py/error.py
  assets/py/item.py
  assets/py/map.py
  assets/py/modules.py
  assets/py/wall.py
  obfuscate_file.py
  package-lock.json
  package.json
  webpack.config.js
Labels: feat, bug-fix

#84 📝 PR: Webpack 적용 bug_fix
  package.json
Labels: bug-fix

#89 📝 PR: 위니브월드 스토리 수정 #88
  assets/css/_markdown.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/data/story/img/story1-1.png
  assets/data/story/img/story1-2.png
  assets/data/story/img/story1.png
  assets/data/story/story.json
  assets/data/story/story1.md
  assets/data/story/story2.md
  assets/js/parser.js
Labels: feat

#90 :bento: Edit: 이미지 이름 변경
  assets/data/story/img/story1-1.png
  assets/data/story/img/story1-2.png
Labels: feat

#92 📝 PR: 라이캣 스프라이트 이미지 수정 #91
  assets/css/_animations.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/img/characters/licat-0.png
  assets/img/characters/licat-1.png
  assets/img/characters/licat-2.png
  assets/img/characters/licat-3.png
  assets/py/character.py
  index.html
Labels: feat

#93 📝 PR: 코드 실행 오류 스타일 수정하기 #36
  assets/css/_notebook.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/py/built_in_functions.py
  assets/py/error.py
Labels: feat

#94 📝 PR: 툴팁 추가하기 #14
  assets/css/_main.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/js/editor.js
  assets/js/event.js
  index.html
Labels: feat
