Repository weniv/weniv_world, pull requests merged in 2023-10, with the labels that each got.

#96 📝 PR: SVG 아이콘 URL 수정 및, 캐릭터 속도에 따른 움직임 버그 수정
  assets/css/_main.scss
  assets/css/_notebook.scss
  assets/css/_story.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/js/editor.js
  assets/py/character.py
  assets/py/error.py
  assets/py/item.py
  decorator_test_file.html
  index.html
  webpack.config.js
Labels: bug, feat, bug-fix

#97 📝 PR: 일부 코드 누락 수정
  assets/css/style.css.map
  assets/py/character.py
Labels: bug-fix

#104 :sparkles: CI/CD 수행시 기존 데이터 `pre_version` 브랜치로 복사 후 main 브랜치 데이터 제거
  .github/workflows/main.yml
Labels: feat

#105 📝 PR: css 경로 수정
  index.html
Labels: bug-fix

#106 📝 PR: css 경로 수정
  webpack.config.js
Labels: bug-fix

#107 📝 PR: Package.json 내 모듈 누락 수정
  package-lock.json
  package.json
Labels: bug-fix

#121 📝 PR: 툴팁 오류 #118
  assets/css/_animations.scss
  assets/css/_main.scss
  assets/css/style.css
  assets/css/style.css.map
  assets/js/event.js
Labels: bug-fix

#128 🐛 Bug: 모달 닫기 버튼 이벤트 동작 확인 #127
  assets/js/event.js
  index.html
Labels: bug-fix

#130 🐛 Bug: 터미널 출력에 따른 크기 변화 및 resizer 재확인 #129
  assets/css/_notebook.scss
  assets/css/_world.scss
  assets/css/style.css
  assets/css/style.css.map
Labels: bug-fix

#132 :sparkles: Add: 캐릭터 정보 모달에 이벤트 리스너 추가 #131
  index.html
Labels: feat

#133 📝 PR: put 함수 생성
  assets/py/built_in_functions.py
  assets/py/character.py
  assets/py/coordinate.py
  assets/py/event.py
  assets/py/item.py
  index.html
Labels: feat

#136 📝 PR: 월드 데이터 다운로드, 업로드 기능 생성
  assets/py/event.py
  index.html
Labels: feat

#137 📝 PR: 아이템 추가시 `item_data`에 추가하는 로직 생성
  index.html
Labels: bug-fix

#140 📝 PR: show_item 버그 수정
  assets/py/built_in_functions.py
Labels: bug-fix

#141 📝 PR: pick 메서드 버그 수정
  assets/py/character.py
Labels: bug-fix
